name: Build and Deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build
        run: |
          npm clean-install
          npm run build
          ls -R dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: dist
          retention-days: 3

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: website
          path: dist

      - name: Anschauen
        run: |
          ls -R dist/
      

      # Benötigen die fertig gebaute Website
      # Credentials/Zugangsdaten für unseren Webserver (S3-Bucket bei AWS)
      # Einloggen beim Webserver
      # Dateien auf den Webserver kopieren
