name: Build and Deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build
        run: |
          npm clean-install
          npm run build
          ls -R dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: dist
          retention-days: 3

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: website
          path: dist

      - name: Anschauen
        run: |
          ls -R dist/
          
      - name: Credentials anschauen
        run: |
          echo "${{ vars.BUCKET_NAME }}"
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      
      # Einloggen beim Webserver
      # Dateien auf den Webserver kopieren
